services:

  mongodb:
    image: mongo:8
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"
    network_mode: host
    volumes:
      - mongodbvol:/data/db

  sa-observer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zex-deposit
    container_name: sa-observer
    entrypoint: poetry run python -m zex_deposit.sa.observer
    network_mode: host
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - ./zex_deposit/dkgs/:/app/zex_deposit/dkgs/
      - /var/log/sa:/var/log/sa
    env_file:
      - .env

  sa-finalizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zex-deposit
    container_name: sa-finalizer
    entrypoint: poetry run python -m zex_deposit.sa.finalizer
    network_mode: host
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - ./zex_deposit/dkgs/:/app/zex_deposit/dkgs/
      - /var/log/sa:/var/log/sa
    env_file:
      - .env
  
  sa-withdrawer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zex-deposit
    container_name: sa-withdrawer
    entrypoint: poetry run python -m zex_deposit.sa.withdrawer
    network_mode: host
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - ./zex_deposit/dkgs/:/app/zex_deposit/dkgs/
      - /var/log/sa:/var/log/sa
    env_file:
      - .env

  sa-sa:
    build:
      context: .
      dockerfile: Dockerfile
    image: zex-deposit
    container_name: sa-sa
    entrypoint: poetry run python -m zex_deposit.sa.sa
    network_mode: host
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - ./zex_deposit/dkgs/:/app/zex_deposit/dkgs/
      - /var/log/sa:/var/log/sa
    env_file:
      - .env

  validator-1:
    build:
      context: .
    image: zex-deposit
    container_name: validator-1
    entrypoint: poetry run python -m zex_deposit.validator.node 0xfd17e3847a110c89925baf6daed35c6f1ddf8bc9c8b38a9bb41096535b5f97fd
    network_mode: host
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - /var/log/validator:/var/log/validator
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env

  validator-2:
    build:
      context: .
    image: zex-deposit
    container_name: validator-2
    entrypoint: poetry run python -m zex_deposit.validator.node 0x0d67cd10c7b7b113b067d42c84a40dee850474892d5647955fdcb7a108b642ed
    network_mode: host
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - /var/log/validator:/var/log/validator
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env

  validator-3:
    build:
      context: .
    image: zex-deposit
    container_name: validator-3
    entrypoint: poetry run python -m zex_deposit.validator.node 0xfe6ec3f9e9ad332de8fcdf8d630ccdc209d54e71fcd9cc866785cebe2db5197b
    network_mode: host
    volumes:
      - ./zex_deposit/data:/app/zex_deposit/data
      - /var/log/validator:/var/log/validator
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env

volumes:
  mongodbvol:
