services:

  mongodb:
    image: mongo:8
    healthcheck:
      test: [ echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet ]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"

  sa-observer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zex-deposit
    container_name: sa-observer
    entrypoint: python -m sa.observer
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./zex_deposit/data:/app/
    env_file:
      - .env

  sa-finalizer:
    build:
      context: .
      dockerfile: Dockerfile
    image: zex-deposit
    container_name: sa-observer
    entrypoint: python -m sa.finalizer
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - .env
